// ── Regex-based dangerous patterns (safety net alongside token analysis) ──

export const dangerousPatterns: { pattern: RegExp; label: string }[] = [
  { pattern: /\brm\b/, label: "rm (any file deletion)" },
  { pattern: /\bsudo\b/i, label: "sudo (privilege escalation)" },
  { pattern: /\b(chmod|chown)\b/i, label: "chmod/chown (permission change)" },
  { pattern: /\bdd\b\s*if=/i, label: "dd (raw disk access)" },
  { pattern: /\bmkfs\b/i, label: "mkfs (filesystem creation)" },
  { pattern: /\bmount\b/i, label: "mount" },
  { pattern: /\b(apt|yum|dnf|pip|npm|uv)\s+install\b/i, label: "package install" },
  { pattern: /\bpython[\d.]*(?:\s|$)/i, label: "python (script execution)" },
  { pattern: /\buv\b/i, label: "uv (python package manager)" },
  { pattern: /\bnode(?:\s|$)/i, label: "node (script execution)" },
  { pattern: /\bruby(?:\s|$)/i, label: "ruby (script execution)" },
  { pattern: /\bperl\s+-[a-z]*i\b/i, label: "perl -i (in-place file modification)" },
  { pattern: /\bphp(?:\s|$)/i, label: "php (script execution)" },
  { pattern: /\blua(?:\s|$)/i, label: "lua (script execution)" },
  { pattern: /\bsed\s+-i(?:\s|$|\.)/i, label: "sed -i (in-place file modification)" },
  { pattern: /\bsed\s+--in-place\b/i, label: "sed --in-place (in-place file modification)" },
  { pattern: /\btruncate\b/i, label: "truncate (in-place size change, can erase contents)" },
  { pattern: /\bbash\s+-[ic]\b/i, label: "bash interactive/command" },
  { pattern: /\beval\b/i, label: "eval" },
  { pattern: /\bsource\b.*\.(?:env|bashrc|profile|secret|local)\b/i, label: "source (config loading)" },
  { pattern: /\bkill\b/i, label: "kill" },
  { pattern: /\bgit\s+push\s+.*--force\b/i, label: "git push --force" },
  { pattern: /\bgit\s+reset\s+.*--hard\b/i, label: "git reset --hard" },
  { pattern: /\bgit\s+clean\s+.*-[fdx]\b/i, label: "git clean (can delete untracked files)" },
  { pattern: /\bcrontab\b/i, label: "crontab" },
  { pattern: /\bnohup\b/i, label: "nohup" },
  { pattern: /\b(screen|tmux)\b/i, label: "screen/tmux" },
  { pattern: /\bssh\b/i, label: "ssh" },
  { pattern: /\b(scp|rsync)\b/i, label: "scp/rsync" },
  { pattern: /\b(curl|wget)\b/i, label: "curl/wget (network access)" },
  // Write-capable file operations
  { pattern: /\b(rmdir|unlink|mv|cp)\b/i, label: "rmdir/unlink/mv/cp (file modification)" },
  { pattern: /\b(patch|install|ln)\b/i, label: "patch/install/ln (file modification)" },
  { pattern: /\btee\b/i, label: "tee (file writing)" },
  { pattern: /\b(tar|zip|unzip|gzip|gunzip)\b/i, label: "tar/zip/unzip/gzip/gunzip (archive operations)" },
  { pattern: /\b(yarn|cargo|go)\b/i, label: "yarn/cargo/go (package manager/build)" },
  // System operations
  { pattern: /\b(shutdown|reboot)\b/i, label: "shutdown/reboot (system power)" },
  { pattern: /\bsystemctl\b/i, label: "systemctl (service management)" },
];
